spring:
  application:
    name: "simple-springboot-api"

logging:
  level:
    org:
      springframework:
        web: "info"

server:
  port: "8080"


management:
  endpoints:
    web:
     exposure:
       include: "prometheus"
  endpoint:
    prometheus:
     enabled: "true"
  metrics:
    export:
     prometheus:
      enabled: "true"
